import { db } from "./db";
import { categories, products, users } from "@shared/schema";
import { eq } from "drizzle-orm";

const categoriesData = [
  {
    id: "cat-1",
    name: "Spices & Herbs",
    nameAr: "البهارات والأعشاب",
    icon: "sun",
    image: "spices",
    productCount: 45,
  },
  {
    id: "cat-2",
    name: "Traditional Clothing",
    nameAr: "الملابس التقليدية",
    icon: "shopping-bag",
    image: "clothing",
    productCount: 32,
  },
  {
    id: "cat-3",
    name: "Food & Groceries",
    nameAr: "الأطعمة والبقالة",
    icon: "coffee",
    image: "food",
    productCount: 78,
  },
  {
    id: "cat-4",
    name: "Home Decor",
    nameAr: "ديكور المنزل",
    icon: "home",
    image: "decor",
    productCount: 23,
  },
  {
    id: "cat-5",
    name: "Beauty & Care",
    nameAr: "الجمال والعناية",
    icon: "heart",
    image: "beauty",
    productCount: 41,
  },
  {
    id: "cat-6",
    name: "Electronics",
    nameAr: "الإلكترونيات",
    icon: "smartphone",
    image: "electronics",
    productCount: 15,
  },
  {
    id: "cat-7",
    name: "Handicrafts",
    nameAr: "الحرف اليدوية",
    icon: "gift",
    image: "handicrafts",
    productCount: 28,
  },
  {
    id: "cat-8",
    name: "Kids & Toys",
    nameAr: "الأطفال والألعاب",
    icon: "star",
    image: "kids",
    productCount: 19,
  },
];

const productsData = [
  {
    id: "prod-1",
    name: "Sudanese Spice Mix - Berbere",
    nameAr: "خلطة بهارات سودانية - بربري",
    description: "Premium blend of traditional Sudanese spices, perfect for stews and grilled meats. Made from authentic recipes passed down through generations.",
    descriptionAr: "خلطة بهارات سودانية تقليدية فاخرة، مثالية للمرق واللحوم المشوية. مصنوعة من وصفات أصيلة متوارثة عبر الأجيال.",
    price: "3.50",
    originalPrice: "4.50",
    images: ["spice1", "spice2", "spice3"],
    categoryId: "cat-1",
    rating: "4.8",
    reviewCount: 124,
    variants: { sizes: ["100g", "250g", "500g"] },
    inStock: true,
    sellerId: "s1",
    sellerName: "Omdurman Spices",
  },
  {
    id: "prod-2",
    name: "Traditional Toub - Gold Embroidery",
    nameAr: "توب تقليدي - تطريز ذهبي",
    description: "Elegant Sudanese toub with intricate gold embroidery. Perfect for special occasions and celebrations.",
    descriptionAr: "توب سوداني أنيق مع تطريز ذهبي رائع. مثالي للمناسبات الخاصة والاحتفالات.",
    price: "85.00",
    images: ["toub1", "toub2"],
    categoryId: "cat-2",
    rating: "4.9",
    reviewCount: 89,
    variants: {
      colors: [
        { name: "White", value: "#FFFFFF" },
        { name: "Cream", value: "#FFFDD0" },
        { name: "Gold", value: "#FFD700" },
      ],
    },
    inStock: true,
    sellerId: "s2",
    sellerName: "Khartoum Textiles",
  },
  {
    id: "prod-3",
    name: "Sudanese Coffee Beans - Jabana",
    nameAr: "بن سوداني - للجبنة",
    description: "Freshly roasted Sudanese coffee beans, perfect for traditional Jabana coffee. Rich aroma with hints of cardamom.",
    descriptionAr: "حبوب بن سودانية محمصة طازجة، مثالية لقهوة الجبنة التقليدية. رائحة غنية مع لمسات من الهيل.",
    price: "8.00",
    originalPrice: "10.00",
    images: ["coffee1", "coffee2"],
    categoryId: "cat-3",
    rating: "4.7",
    reviewCount: 256,
    variants: { sizes: ["250g", "500g", "1kg"] },
    inStock: true,
    sellerId: "s3",
    sellerName: "Nile Coffee Co.",
  },
  {
    id: "prod-4",
    name: "Handwoven Basket - Colorful",
    nameAr: "سلة منسوجة يدوياً - ملونة",
    description: "Beautiful handwoven basket made by Sudanese artisans. Perfect for home decoration or storage.",
    descriptionAr: "سلة منسوجة يدوياً جميلة من صنع حرفيين سودانيين. مثالية لديكور المنزل أو التخزين.",
    price: "25.00",
    images: ["basket1", "basket2"],
    categoryId: "cat-7",
    rating: "4.6",
    reviewCount: 43,
    variants: { sizes: ["Small", "Medium", "Large"] },
    inStock: true,
    sellerId: "s4",
    sellerName: "Sudanese Crafts",
  },
  {
    id: "prod-5",
    name: "Hibiscus Tea - Karkade",
    nameAr: "شاي الكركديه",
    description: "Premium dried hibiscus flowers for refreshing Karkade tea. Rich in antioxidants and vitamin C.",
    descriptionAr: "زهور كركديه مجففة فاخرة لشاي الكركديه المنعش. غني بمضادات الأكسدة وفيتامين سي.",
    price: "5.50",
    images: ["karkade1", "karkade2"],
    categoryId: "cat-3",
    rating: "4.9",
    reviewCount: 312,
    variants: { sizes: ["100g", "250g", "500g"] },
    inStock: true,
    sellerId: "s5",
    sellerName: "Sudan Naturals",
  },
  {
    id: "prod-6",
    name: "Silver Bracelet - Traditional Design",
    nameAr: "إسوارة فضية - تصميم تقليدي",
    description: "Handcrafted silver bracelet featuring traditional Sudanese patterns. A beautiful piece of wearable art.",
    descriptionAr: "إسوارة فضية مصنوعة يدوياً بأنماط سودانية تقليدية. قطعة فنية جميلة يمكن ارتداؤها.",
    price: "45.00",
    originalPrice: "55.00",
    images: ["bracelet1", "bracelet2"],
    categoryId: "cat-7",
    rating: "4.8",
    reviewCount: 67,
    inStock: true,
    sellerId: "s6",
    sellerName: "Nubian Jewelry",
  },
  {
    id: "prod-7",
    name: "Sudanese Dates - Premium",
    nameAr: "تمر سوداني - فاخر",
    description: "Sweet and soft premium Sudanese dates. Perfect for snacking or gifting.",
    descriptionAr: "تمر سوداني فاخر حلو وطري. مثالي للتناول كوجبة خفيفة أو كهدية.",
    price: "12.00",
    images: ["dates1", "dates2"],
    categoryId: "cat-3",
    rating: "4.7",
    reviewCount: 189,
    variants: { sizes: ["500g", "1kg", "2kg"] },
    inStock: true,
    sellerId: "s7",
    sellerName: "Nile Valley Dates",
  },
  {
    id: "prod-8",
    name: "Incense - Bakhoor Sudani",
    nameAr: "بخور سوداني",
    description: "Traditional Sudanese incense with a rich, warm fragrance. Perfect for creating a welcoming atmosphere.",
    descriptionAr: "بخور سوداني تقليدي برائحة غنية ودافئة. مثالي لخلق جو ترحيبي.",
    price: "15.00",
    images: ["incense1", "incense2"],
    categoryId: "cat-4",
    rating: "4.9",
    reviewCount: 98,
    inStock: true,
    sellerId: "s8",
    sellerName: "Sudan Fragrances",
  },
  {
    id: "prod-9",
    name: "Sudanese Henna - Natural",
    nameAr: "حناء سودانية طبيعية",
    description: "100% natural Sudanese henna for beautiful body art and hair care.",
    descriptionAr: "حناء سودانية طبيعية 100% لفن الجسم الجميل والعناية بالشعر.",
    price: "6.00",
    images: ["henna1", "henna2"],
    categoryId: "cat-5",
    rating: "4.8",
    reviewCount: 156,
    variants: { sizes: ["50g", "100g", "200g"] },
    inStock: true,
    sellerId: "s9",
    sellerName: "Sudan Beauty",
  },
  {
    id: "prod-10",
    name: "Traditional Jalabiya - Men",
    nameAr: "جلابية رجالية تقليدية",
    description: "Comfortable and elegant men's jalabiya in traditional Sudanese style.",
    descriptionAr: "جلابية رجالية مريحة وأنيقة بالطراز السوداني التقليدي.",
    price: "35.00",
    images: ["jalabiya1", "jalabiya2"],
    categoryId: "cat-2",
    rating: "4.7",
    reviewCount: 78,
    variants: {
      sizes: ["M", "L", "XL", "XXL"],
      colors: [
        { name: "White", value: "#FFFFFF" },
        { name: "Beige", value: "#F5F5DC" },
      ],
    },
    inStock: true,
    sellerId: "s10",
    sellerName: "Khartoum Fashion",
  },
  {
    id: "prod-11",
    name: "Peanut Butter - Sudanese Style",
    nameAr: "زبدة الفول السوداني - طريقة سودانية",
    description: "Creamy peanut butter made the traditional Sudanese way. No additives.",
    descriptionAr: "زبدة فول سوداني كريمية مصنوعة بالطريقة السودانية التقليدية. بدون إضافات.",
    price: "4.50",
    images: ["peanut1"],
    categoryId: "cat-3",
    rating: "4.6",
    reviewCount: 234,
    variants: { sizes: ["250g", "500g"] },
    inStock: true,
    sellerId: "s11",
    sellerName: "Sudan Foods",
  },
  {
    id: "prod-12",
    name: "Wooden Prayer Beads",
    nameAr: "مسبحة خشبية",
    description: "Handcrafted wooden prayer beads from Sudan. Beautiful craftsmanship.",
    descriptionAr: "مسبحة خشبية مصنوعة يدوياً من السودان. حرفية جميلة.",
    price: "8.00",
    images: ["beads1", "beads2"],
    categoryId: "cat-7",
    rating: "4.9",
    reviewCount: 112,
    inStock: true,
    sellerId: "s12",
    sellerName: "Sudan Crafts",
  },
];

export async function seedDatabase() {
  console.log("Starting database seeding...");

  try {
    const existingCategories = await db.select().from(categories).limit(1);
    if (existingCategories.length > 0) {
      console.log("Database already seeded, skipping...");
      return;
    }

    console.log("Seeding categories...");
    await db.insert(categories).values(categoriesData);

    console.log("Seeding products...");
    await db.insert(products).values(productsData);

    console.log("Database seeding completed!");
  } catch (error) {
    console.error("Error seeding database:", error);
    throw error;
  }
}
